---
title: "Publicly funded services locations"
output: 
  html_notebook:
    code_folding: hide
---


```{r include=FALSE}
#~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~#
# LOAD LIBRARIES #
#~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~#

library(tidyverse)
library(lubridate)
library(glue)
library(fastDummies)
library(sf)
library(tmap)
library(gtsummary)
library(plm)
library(fuzzyjoin)
library(sqldf)

#~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~#
# GLOBAL PARAMS #
#~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~#

data_dir <- "data_download"
comitted_data <- "other_data"

#~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~#
# LOAD THE DATA #
#~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Load the IMD scores and ranks #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

IMD_2010_income <- read_csv(paste(data_dir, "IMD_2010_income.csv", sep = "/")) %>% 
  mutate(Measurement = "Score",
         `Indices of Deprivation` = "b. Income Deprivation Domain")
IMD_2015 <- read_csv(paste(data_dir, "IMD_2015.csv", sep = "/")) 
IMD_2019 <- read_csv(paste(data_dir, "IMD_2019.csv", sep = "/")) 

# a. Index of Multiple Deprivation (IMD)                    
# b. Income Deprivation Domain                              
# c. Employment Deprivation Domain                          
# d. Education, Skills and Training Domain                  
# e. Health Deprivation and Disability Domain               
# f. Crime Domain                                           
# g. Barriers to Housing and Services Domain                
# h. Living Environment Deprivation Domain                  
# i. Income Deprivation Affecting Children Index (IDACI)    
# j. Income Deprivation Affecting Older People Index (IDAOPI)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Load the geographic information #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#


# # Load the LSOA shapes
LSOA_2011 <- read_sf(paste(data_dir, 
                           "LSOA2011_boundaries",
                           "Lower_Layer_Super_Output_Areas_December_2011_Generalised_Clipped__Boundaries_in_England_and_Wales.shp", 
                           sep = "/"))

LSOA_2011 <- LSOA_2011 %>%
  st_make_valid()

# and lookups
LSOA_2001_2011_lookup <- read_csv(paste(comitted_data,
                                        "Lower_Layer_Super_Output_Area_(2001)_to_Lower_Layer_Super_Output_Area_(2011)_to_Local_Authority_District_(2011)_Lookup_in_England_and_Wales.csv",
                                        sep = "/"))

LSOA_city_lookup <- read_csv(paste(comitted_data,
                                   "Lower_Layer_Super_Output_Area_(2011)_to_Major_Towns_and_Cities_(December_2015)_Lookup_in_England_and_Wales.csv",
                                   sep = "/"))
LSOA_rural_urban <- read_csv(paste(comitted_data,
                                   "Rural_Urban_Classification_(2011)_of_Lower_Layer_Super_Output_Areas_in_England_and_Wales.csv",
                                   sep = "/"))

OA_region_lookup <- read_csv(paste(data_dir,
                                   "(December_2017)_Lookup_with_Area_Classifications_in_Great_Britain.csv",
                                   sep = "/"))


LSOA_region_lookup <- OA_region_lookup %>%
  select(-starts_with("OA"), -FID) %>%
  distinct()

# # check uniqueness on LSOA
# LSOA_region_check <- LSOA_region_lookup %>%
#   count(LSOA11CD) %>%
#   arrange(-n) %>%
#   filter(n != 1)

LA_shapes <- read_sf(paste(data_dir, 
                           "la_shapes",
                           "Local_Authority_Districts_(December_2019)_Boundaries_UK_BUC.shp", 
                           sep = "/"))

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Load the public services locations #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Legal aid
legalaid_work <- read_csv(paste(data_dir,
                                "legalaid_work_locations", 
                                "legal-aid-statistics-civil-starts-provider-location-data-to-mar-2021.csv", 
                                sep = "/"))

# GPs
gp_locations <- read_csv(paste(data_dir, "gp_locations", "epraccur.csv", sep = "/"),
                         col_names = FALSE)

# Jobcentres
jobcentre_locations <- read_csv(paste(data_dir, "jobcentre_locations.csv", sep = "/"))
jobcentre_register <- read_csv(paste(data_dir, "jobcentre_register.csv", sep = "/"))


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Load thelookups                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Load the uprn file
# Note that it changes name depending on when it was downloaded so the first two lines just look for it
uprn_dir_files <- list.files(paste(data_dir, "uprns", sep = "/"))
uprn_file <- uprn_dir_files %>% keep(~str_detect(.x, ".csv"))
#UPRNs <- read_csv(paste(data_dir, "uprns", uprn_file, sep = "/"))

uprn_list <- jobcentre_register %>% filter(!is.na(address)) %>% pull(address) %>% format() %>% paste(collapse = ", ")

UPRNs_short  <- read.csv.sql(paste(data_dir, "uprns", uprn_file, sep = "/"),
                             sql = glue("select * from file where UPRN in ({uprn_list})"))

# Load the ONSPD
onspd <- read_csv(paste(data_dir, "onspd", "Data/ONSPD_FEB_2021_UK.csv", sep = "/"))

#~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~#
# CREATE MAIN DATAFILE #
# This section puts    #
# the above data       #
# together to create   #
# the dataframe from   #
# which everything is  #
# run.                 #
#~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~#

IMD_2010_income_LSOA11 <- IMD_2010_income %>%
  left_join(LSOA_2001_2011_lookup %>% select(LSOA01CD, LSOA11CD),
            by = c("FeatureCode" = "LSOA01CD")) %>%
  mutate(FeatureCode = LSOA11CD) %>%
  group_by(FeatureCode, DateCode, Measurement, `Indices of Deprivation`) %>%
  summarise(Value = mean(Value),
            .groups = "drop")

# Create a dataframe with one row per LSOA and all the measurements for each year
process_IMD_file <- .  %>%
  filter(Measurement == "Score") %>%
  transmute(FeatureCode, DateCode, Value, index = str_sub(`Indices of Deprivation`, 1, 1)) %>% 
  pivot_wider(names_from = c(DateCode, index),
              values_from = Value,
              names_glue = "{index}_{DateCode}") %>%
  select(FeatureCode, sort(tidyselect::peek_vars()))

IMD_main <- IMD_2019 %>% process_IMD_file() %>%
  full_join(IMD_2015 %>% process_IMD_file(),
            by = "FeatureCode") %>%
  full_join(IMD_2010_income_LSOA11  %>% process_IMD_file(),
            by = "FeatureCode")

IMD_main_long <- IMD_main  %>%
  pivot_longer(matches("[a-z]_[0-9]{4}"), names_to = "measure_year") %>%
  separate(col = "measure_year", into = c("measure", "year")) %>%
  pivot_wider(names_from = "measure", values_from = "value")

# 
# # Join this to the LSOA shape file
# LSOA_IMD_main <- LSOA_2011 %>%
#   right_join(IMD_main, # just keep where we have IMD scores
#              by = c("lsoa11cd" = "FeatureCode"))
# 
# 
# LSOA_IMD_main_long <- LSOA_2011 %>%
#   right_join(IMD_main_long, # just keep where we have IMD scores
#              by = c("lsoa11cd" = "FeatureCode"))



# Create the locations of public services dataframe

# Process the specific formats of the input into a temp file
gp_locations_temp <- gp_locations %>%
  left_join(onspd,
            by = c("X10" = "pcds")) %>%
  mutate(service = "GP") %>%
  filter(rgn != "S99999999") # remove Scotland :(

gp_locations_temp_byyear <- gp_locations_temp %>%
  count(X10, lat, long) %>%
  mutate(service = "gp",
         year = list(c("2010", "2015", "2019")))%>%
  unnest(year)

# Process the specific formats of the input into a temp file
jobcentre_locations_temp <- jobcentre_locations %>%
  left_join(onspd,
            by = c("Postcode" = "pcds"))# %>%
# mutate(service = "jobcentre") %>%
# filter(rgn != "S99999999") # remove Scotland :(


jobcentre_register_temp <- jobcentre_register %>%
  left_join(UPRNs_short %>% mutate(UPRN = as.numeric(UPRN)),
            by = c("address" = "UPRN"))


jobcentre_locations_temp_join <- jobcentre_locations_temp %>%
  transmute(`Jobcentre Office` = stringi::stri_enc_toutf8(`Jobcentre Office`, validate = TRUE) %>% tolower(),
            Postcode,
            lat1 = lat,
            long1 = long) %>%
  full_join(jobcentre_register_temp %>%
              transmute(name = stringi::stri_enc_toutf8(name, validate = TRUE) %>% tolower(),
                        address,
                        lat2 = LATITUDE,
                        long2 = LONGITUDE,
                        `start-date`,
                        `end-date`),
            by = c("Jobcentre Office" = "name")) %>%
  rowwise() %>%
  mutate(lat = coalesce(lat1, lat2),
         long = coalesce(long1, long2)) %>%
  ungroup()

# jobcentre_locations_temp_join %>% filter(is.na(lat))

jobcentre_locations_temp_join_byyear <- jobcentre_locations_temp_join %>%
  filter(!is.na(lat)) %>%
  group_by(lat, long) %>%
  summarise(start_date = coalesce(`start-date`),
            end_date = coalesce(`end-date`),
            .groups = "drop") %>%
  mutate(`2010` = if_else((is.na(start_date) | start_date < ymd("2010-01-01")) & (is.na(end_date) | end_date >= ymd("2011-01-01")),
                          "2010", NA_character_),
         `2015` = if_else((is.na(start_date) | start_date < ymd("2015-01-01")) & (is.na(end_date) | end_date >= ymd("2016-01-01")),
                          "2015", NA_character_),
         `2019` = if_else((is.na(start_date) | start_date < ymd("2019-01-01")) & (is.na(end_date) | end_date >= ymd("2020-01-01")),
                          "2019", NA_character_)) %>%
  pivot_longer(matches("[0-9]{4}"), values_to = "year") %>%
  filter(!is.na(year)) %>%
  select(lat, long, year) %>%
  mutate(service = "jobcentre")


# Process the specific formats of the input into a temp file
legalaid_locations_temp <- legalaid_work %>%
  filter(fin_yr == "2019-20",
         scheme == "Legal Help") %>%
  count(Postcode, lat, long) %>%
  mutate(service = "legal aid")

legalaid_locations_temp_byyear <- legalaid_work %>%
  filter(scheme == "Legal Help",
         typecode == "HOU") %>%
  mutate(year = str_sub(fin_yr, 1, 4)) %>% #todo
  filter(year %in% c("2010", "2015", "2019")) %>%
  count(year, Postcode, lat, long) %>%
  mutate(service = "legal aid")

# # Put these together into a single data frame
# services_main <- bind_rows(#gp_locations2 %>% select(service, lat, long),
#   jobcentre_locations_temp %>% select(service, lat, long),
#   legalaid_locations_temp %>% select(service, lat, long)) %>%
#   filter(lat <= 90,
#          !is.na(lat)) %>%
#   st_as_sf(coords = c("long", "lat"), crs = "WGS84")
# 
# # services_multipoint <- services_main %>%
# #   group_by(service) %>%
# #   summarise(a = st_combine(geometry))
# 
# services_multipoint <- services_main %>%
#   split(services_main$service) %>%
#   imap(~.x %>% st_combine() %>% st_sf %>% mutate(service = .y)) %>% 
#   bind_rows()

services_multipoint_byyear <- bind_rows(legalaid_locations_temp_byyear,
                                        jobcentre_locations_temp_join_byyear,
                                        gp_locations_temp_byyear) %>%
  
  filter(lat <= 90,
         !is.na(lat)) %>%
  st_as_sf(coords = c("long", "lat"), crs = "WGS84") %>%
  group_by(service, year) %>%
  summarise(a = st_combine(geometry),
            .groups = "drop")


# This is the distance to the nearest service for each LSOA
# Will be zero where the service is in the LSOA
dist_all_temp <- LSOA_2011 %>%
  st_distance(services_multipoint_byyear) %>%
  as_tibble() %>%
  setNames(services_multipoint_byyear %>% {paste0("nearest_", pull(.,service), ":", pull(.,year)) %>% str_replace_all(" ", "_")})

LSOA_with_dist_byyear <- LSOA_2011 %>%
  bind_cols(dist_all_temp) %>%
  as_tibble() %>%
  select(lsoa11cd, starts_with("nearest_")) %>%
  pivot_longer(cols = starts_with("nearest_"), names_to = "nearest_service") %>%
  separate(nearest_service, c("service", "year"), sep = ":") %>%
  pivot_wider(names_from = "service", values_from = "value")

```


```{r}


IMD_main_panel <- IMD_main_long %>%
  left_join(LSOA_with_dist_byyear,
            by = c("FeatureCode" = "lsoa11cd",
                   "year" = "year"))


# LSOA_lookup <- onspd %>%
#   filter(!is.na(rgn)) %>%
#   count(lsoa11, rgn) %>%
#   group_by(lsoa11) %>%
#   slice(which.max(n))

IMD_main_panel <- IMD_main_panel %>%
  # arrange(FeatureCode, year) %>%
  # group_by(FeatureCode) %>%
  # mutate(sum_close_legal_aid = sum(close_legal_aid),
  #        n_periods = n()) %>%
  # ungroup() %>%
  left_join(LSOA_city_lookup,
            by = c("FeatureCode" = "LSOA11CD")) %>%
  left_join(LSOA_rural_urban, 
            by = c("FeatureCode" = "LSOA11CD")) %>%
  left_join(LSOA_region_lookup,
            by = c("FeatureCode" = "LSOA11CD"))

# IMD_main_panel_change <- IMD_main_panel %>%
#   filter(sum_close_legal_aid > 0,
#          sum_close_legal_aid < 3)





# IMD_main_panel_change %>%
#   ggplot(aes(as.numeric(nearest_legal_aid), b)) +
#   geom_point()

near <- 2
far <- 4

IMD_main_panel <- IMD_main_panel %>%
  mutate(across(starts_with("nearest"), ~if_else(.x <= units::as_units(near, "miles"), 1, 0), .names = "close_{.col}_near"),
         across(starts_with("nearest"), ~if_else(.x >= units::as_units(far, "miles"), 1, 0), .names = "close_{.col}_far")) %>%
  rename_with(~str_remove(.x, "_nearest"))# %>%
#mutate(combo_bonus = if_else(close_jobcentre + close_legal_aid == 2, 1, 0))

a <- LSOA_city_lookup %>%
  count(TCITY15NM)

RoIs <- LSOA_2011 %>%
  left_join(LSOA_city_lookup,
            by = c("lsoa11cd" = "LSOA11CD")) %>%
  mutate(RoI = case_when(TCITY15NM == "London" ~ "London",
                         TCITY15NM %in% c("Leeds",
                                          "Manchester", 
                                          "Liverpool",
                                          "Sheffield"
                                          #"Preston",
                                          #"Barnsely",
                                          #"Bolton",
                                          #"Wigan",
                                          #"Bradford",
                                          #"Blackpool",
                                          #"Birmingham",
                                          #"Doncaster",
                                          #"Mansfield",
                                          #"Nottingham",
                                          #"Leicester"
                                          #"Warrington",
                                          #"Wakefield"
                         ) ~ "Northern cities",
                         TRUE ~ NA_character_)) 


RoI_North <- RoIs %>%
  filter(RoI == "Northern cities") %>%
  st_combine() %>%
  st_make_valid() %>%
  st_buffer(dist = units::as_units(5, "miles"))

# RoI_North <- st_bbox(c(xmin = -16.1, xmax = 16.6, ymax = 85, ymin = 51), crs = st_crs("WGS84")) %>%
#   st_as_sfc()

RoI_London <- RoIs %>%
  filter(RoI == "London") %>%
  st_combine() %>%
  st_make_valid() %>%
  st_buffer(dist = units::as_units(10, "miles"))



LSOA_2011_RoI <- LSOA_2011 %>% 
  mutate(London_RoI = lengths(st_intersects(LSOA_2011, RoI_London)) > 0,
         North_RoI = lengths(st_intersects(LSOA_2011, RoI_North)) > 0)

LSOA_2011_RoI_northcodes <- LSOA_2011_RoI %>%
  filter(North_RoI) %>% 
  pull(lsoa11cd)

LSOA_2011_RoI_londoncodes <- LSOA_2011_RoI %>%
  filter(London_RoI) %>% 
  pull(lsoa11cd)

IMD_fd_2015_2019 <- IMD_main_panel %>%
  filter(year %in% c("2015", "2019")) %>%
  arrange(year) %>%
  group_by(FeatureCode) %>%
  summarise(close_legal_aid_near_fd = 
              close_legal_aid_near[2] - close_legal_aid_near[1],
            close_legal_aid_far_fd = 
              close_legal_aid_far[2] - close_legal_aid_far[1])

map_fd_near <- LSOA_2011 %>%
  left_join(IMD_fd_2015_2019,
            by = c("lsoa11cd" = "FeatureCode")) %>%
  filter(close_legal_aid_near_fd != 0) %>%
  #filter(CTRY11NM == "England") %>%
  tm_shape() +
  tm_fill(col = "close_legal_aid_near_fd",
          title = "",
          style = "cat",
          palette = "Pastel1",
          legend.format=list(fun=function(x) if_else(x<0, 
                                                     glue("{x} Became not near"),
                                                     glue("+{x} Became near")))) +
  tm_shape(LA_shapes) +
  tm_borders(alpha = 0.2) +
  tm_shape(LSOA_2011_RoI %>% filter(London_RoI) %>% st_combine() %>% st_make_valid()) +
  tm_borders() + 
  tm_layout(glue("First difference 2015 to 2019:\nLSOAs within {near} miles"),
            legend.title.size = 2,
            legend.text.size = 1.2)

#+
# tm_shape(LSOA_2011_RoI %>% filter(North_RoI) %>% st_combine() %>% st_make_valid()) +
# tm_borders()

tmap_save(map_fd_near,
          filename = "outputs/legal_aid_near_fd.png")



```

```{r}
map_fd_far <- LSOA_2011 %>%
  left_join(IMD_fd_2015_2019,
            by = c("lsoa11cd" = "FeatureCode")) %>%
  filter(close_legal_aid_far_fd != 0) %>%
  #filter(CTRY11NM == "England") %>%
  tm_shape() +
  tm_fill(col = "close_legal_aid_far_fd",
          title = "",
          style = "cat",
          palette = "Pastel1",
          legend.format=list(fun=function(x)  if_else(x<0, 
                                                     glue("{x} Became not far"),
                                                     glue("+{x} Became far")))) +
  tm_shape(LA_shapes) +
  tm_borders(alpha = 0.2) +
  tm_shape(LSOA_2011_RoI %>% filter(London_RoI) %>% st_combine() %>% st_make_valid()) +
  tm_borders() + 
  tm_layout(glue("First difference 2015 to 2019:\nLSOAs over {far} miles"),
            legend.title.size = 2,
            legend.text.size = 1.2)

tmap_save(map_fd_far,
          filename = "outputs/legal_aid_far_fd.png")

```


```{r}

input_data <- IMD_main_panel %>% filter(year == "2019")

m1 <- lm(b ~ close_legal_aid_near + close_legal_aid_far + close_jobcentre_near + close_jobcentre_far + close_gp_far + close_gp_near,
         data = input_data)

t1 <- m1 %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)

m2 <- lm(b ~ RUC11 + close_legal_aid_near + close_legal_aid_far + close_jobcentre_near + close_jobcentre_far + close_gp_far + close_gp_near,
         data = input_data)

t2 <- m2 %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)

a <- tbl_merge(
  tbls = list(t1, t2),
  tab_spanner = c("**No controls**", "**Rural/Urban controls**")
) %>%
  as_gt() %>%
  gt::text_transform(locations = gt::cells_body(columns = label),
                     \(x) case_when(x == "close_legal_aid_near" ~ glue("Legal aid: within {near} miles"),
                                    x == "close_legal_aid_far" ~ glue("Legal aid: over {far} miles"),
                                    x == "close_jobcentre_near" ~ glue("Jobcentre: within {near} miles"),
                                    x == "close_jobcentre_far" ~ glue("Jobcentre: over {far} miles"),
                                    x == "close_gp_near" ~ glue("GP: within {near} miles"),
                                    x == "close_gp_far" ~ glue("GP: over {far} miles"),
                                    x == "RUC11" ~ glue("ONS Rural/Urban classification"),
                                    TRUE ~ x)) %>%
  gt::tab_header("Income deprivation proportion by LSOA, 2019") %>%
  gt::tab_footnote(glue("n = 82,344;
                      R^2 = {m1 %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**No controls**")) %>%
  gt::tab_footnote(glue("n = 82,344;
                      R^2 = {m2 %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**Rural/Urban controls**")) %>%
  gt::gtsave(filename = "outputs/ols_2019.html")

```


```{r}

data_plm <- IMD_main_panel

plm_out_fd <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "fd",
                  #effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fd <- plm_out_fd %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)


plm_out_fe <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "within",
                  effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fe <- plm_out_fe %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)

tbl_merge(
  tbls = list(tbl_plm_out_fd, tbl_plm_out_fe),
  tab_spanner = c("**First difference**", "**Fixed effects**")
) %>%
  as_gt() %>%
  gt::text_transform(locations = gt::cells_body(columns = label),
                     \(x) case_when(x == "close_legal_aid_near" ~ glue("Legal aid: within {near} miles"),
                                    x == "close_legal_aid_far" ~ glue("Legal aid: over {far} miles"),
                                    TRUE ~ x)) %>%
  gt::tab_header("Income deprivation proportion by LSOA, England") %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fd %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**First difference**")) %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fe %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**Fixed effects**")) %>%
  gt::gtsave(filename = "outputs/plm_all.html")

```

```{r}

data_plm <- IMD_main_panel %>%
  filter(FeatureCode %in% LSOA_2011_RoI_londoncodes)

plm_out_fd <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "fd",
                  #effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fd <- plm_out_fd %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)


plm_out_fe <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "within",
                  effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fe <- plm_out_fe %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)

tbl_merge(
  tbls = list(tbl_plm_out_fd, tbl_plm_out_fe),
  tab_spanner = c("**First difference**", "**Fixed effects**")
) %>%
  as_gt() %>%
  gt::text_transform(locations = gt::cells_body(columns = label),
                     \(x) case_when(x == "close_legal_aid_near" ~ glue("Legal aid: within {near} miles"),
                                    x == "close_legal_aid_far" ~ glue("Legal aid: over {far} miles"),
                                    TRUE ~ x)) %>%
  gt::tab_header("Income deprivation proportion by LSOA, London + 10 miles") %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fd %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**First difference**")) %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fe %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**Fixed effects**")) %>%
  gt::gtsave(filename = "outputs/plm_london.html")

```


```{r}

data_plm <- IMD_main_panel %>%
  filter(!(FeatureCode %in% LSOA_2011_RoI_londoncodes))

plm_out_fd <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "fd",
                  #effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fd <- plm_out_fd %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)


plm_out_fe <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "within",
                  effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fe <- plm_out_fe %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)

tbl_merge(
  tbls = list(tbl_plm_out_fd, tbl_plm_out_fe),
  tab_spanner = c("**First difference**", "**Fixed effects**")
) %>%
  as_gt() %>%
  gt::text_transform(locations = gt::cells_body(columns = label),
                     \(x) case_when(x == "close_legal_aid_near" ~ glue("Legal aid: within {near} miles"),
                                    x == "close_legal_aid_far" ~ glue("Legal aid: over {far} miles"),
                                    TRUE ~ x)) %>%
  gt::tab_header("Income deprivation proportion by LSOA, Outside London") %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fd %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**First difference**")) %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fe %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**Fixed effects**")) %>%
  gt::gtsave(filename = "outputs/plm_nonlondon.html")

```

```{r}

data_plm <- IMD_main_panel %>%
  filter((FeatureCode %in% LSOA_2011_RoI_northcodes))

plm_out_fd <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "fd",
                  #effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fd <- plm_out_fd %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)


plm_out_fe <- plm(b ~ close_legal_aid_near + close_legal_aid_far,
                  data = data_plm,
                  model = "within",
                  effect = "twoways"
)

#summary(plm_out)

tbl_plm_out_fe <- plm_out_fe %>%
  tbl_regression(intercept = TRUE,
                 estimate_fun = \(x) style_sigfig(x, digits = 3)) %>%
  add_significance_stars(hide_ci = FALSE,
                         hide_se = TRUE)

tbl_merge(
  tbls = list(tbl_plm_out_fd, tbl_plm_out_fe),
  tab_spanner = c("**First difference**", "**Fixed effects**")
) %>%
  as_gt() %>%
  gt::text_transform(locations = gt::cells_body(columns = label),
                     \(x) case_when(x == "close_legal_aid_near" ~ glue("Legal aid: within {near} miles"),
                                    x == "close_legal_aid_far" ~ glue("Legal aid: over {far} miles"),
                                    TRUE ~ x)) %>%
  gt::tab_header("Income deprivation proportion by LSOA, Outside London") %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fd %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**First difference**")) %>%
  gt::tab_footnote(glue("n = 82,344; T = 3;
                      R^2 = {plm_out_fe %>% broom::glance() %>% pull(r.squared) %>% format(digits = 2)}"),
                   gt::cells_column_spanners("**Fixed effects**")) %>%
  gt::gtsave(filename = "outputs/plm_north.html")

```

```{r message=FALSE}
# we can plot:
# services_multipoint_byyear
# LSOA_2011 (boundaries)
# IMD_main_panel

# LA_shape <- LSOA_2011 %>%
#   left_join(LSOA_region_lookup,
#             by = c("lsoa11cd" = "LSOA11CD")) %>%
#   filter(CTRY11NM == "England") %>%
#   group_by(LAD17NM) %>%
#   st_union() %>%
#   st_make_valid()

IMD_shapes_2019 <- LSOA_2011 %>%
  left_join(IMD_main_panel %>% filter(year == "2019"),
            by = c("lsoa11cd" = "FeatureCode")) %>%
  filter(CTRY11NM == "England",
         !is.na(b))

IMD_shapes_2015 <- LSOA_2011 %>%
  left_join(IMD_main_panel %>% filter(year == "2015"),
            by = c("lsoa11cd" = "FeatureCode")) %>%
  filter(CTRY11NM == "England",
         !is.na(b))

IMD_shapes_2010 <- LSOA_2011 %>%
  left_join(IMD_main_panel %>% filter(year == "2010"),
            by = c("lsoa11cd" = "FeatureCode")) %>%
  filter(CTRY11NM == "England",
         !is.na(b))

breaks = seq(0,8) * 0.1

tmap_mode("plot")
id_map_england_2019 <- tm_basemap("Stamen.TonerLite") +
  tm_shape(IMD_shapes_2019 %>% mutate(`Income deprivation` = b)) + 
  tm_fill(col = "Income deprivation",
          style = "fixed",
          breaks = breaks,
          legend.format=list(fun=function(x) paste0(formatC(x*100, digits=0, format="f"), "%"))) +
  tm_shape(LA_shapes) +
  tm_borders(alpha = 0.2) + 
  tm_layout(legend.title.size = 2,
            legend.text.size = 1.5)

tmap_save(id_map_england_2019,
          filename = "outputs/id_map_england_2019.png")

id_map_england_2015 <- tm_basemap("Stamen.TonerLite") +
  tm_shape(IMD_shapes_2015 %>% mutate(`Income deprivation` = b)) + 
  tm_fill(col = "Income deprivation",
          style = "fixed",
          breaks = breaks,
          legend.format=list(fun=function(x) paste0(formatC(x*100, digits=0, format="f"), "%"))) +
  tm_shape(LA_shapes) +
  tm_borders(alpha = 0.2) + 
  tm_layout(legend.title.size = 2,
            legend.text.size = 1.5)

tmap_save(id_map_england_2015,
          filename = "outputs/id_map_england_2015.png")

id_map_england_2010 <- tm_basemap("Stamen.TonerLite") +
  tm_shape(IMD_shapes_2010 %>% mutate(`Income deprivation` = b)) + 
  tm_fill(col = "Income deprivation",
          style = "fixed",
          breaks = breaks,
          legend.format=list(fun=function(x) paste0(formatC(x*100, digits=0, format="f"), "%"))) +
  tm_shape(LA_shapes) +
  tm_borders(alpha = 0.2) + 
  tm_layout(legend.title.size = 2,
            legend.text.size = 1.5)

tmap_save(id_map_england_2010,
          filename = "outputs/id_map_england_2010.png")

IMD_main_wide <- IMD_main_panel %>%
   pivot_wider(names_from = year,
               values_from = -c(FeatureCode, year)) %>%
   mutate(b_diff = b_2019 - b_2010)

IMD_shapes_diff <- LSOA_2011 %>%
  inner_join(IMD_main_wide,
             by = c("lsoa11cd" = "FeatureCode")) %>%
  filter(!is.na(b_diff))

id_map_england_diff <- tm_basemap("Stamen.TonerLite") +
  tm_shape(IMD_shapes_diff %>% mutate(`Income deprivation change` = b_diff)) + 
  tm_fill(col = "Income deprivation change",
          title = "Income deprivation\nchange",
          style = "fixed",
          breaks = c(-Inf, -0.05, 0.05, Inf),
          pallette = "-RdYlGn",
          legend.format=list(fun=function(x) paste0(formatC(x*100, digits=0, format="f"), "%"))) +
  tm_shape(LA_shapes) +
  tm_borders(alpha = 0.2) + 
  tm_layout(legend.title.size = 2,
            legend.text.size = 1.5)

tmap_save(id_map_england_diff,
          filename = "outputs/id_map_england_diff.png")
```

